# Generated by Django 5.0.6 on 2024-05-23 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('district_short_code', models.CharField(max_length=50)),
                ('div_sec_area', models.CharField(max_length=100)),
                ('div_sec_area_short_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fullname', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User1',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.user')),
                ('telephoneNo', models.CharField(default='0000000000', max_length=20)),
                ('city', models.CharField(default='Default City', max_length=100)),
                ('managementLevel', models.CharField(default='Default Management Level', max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('api.user',),
        ),
        migrations.CreateModel(
            name='User2',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.user')),
                ('district', models.CharField(default='Default District', max_length=100)),
                ('divsec', models.CharField(default='Default Divsec', max_length=100)),
                ('firstName', models.CharField(default='Default firstName', max_length=100)),
                ('lastName', models.CharField(default='Default lastName', max_length=100)),
                ('address', models.CharField(default='Default Address', max_length=255)),
                ('telephoneNo', models.CharField(default='0000000000', max_length=20)),
                ('location', models.CharField(default='Default Location', max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('api.user',),
        ),
        migrations.CreateModel(
            name='User3',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.user')),
                ('telephoneNo', models.CharField(default='0000000000', max_length=20)),
                ('city', models.CharField(default='Default City', max_length=100)),
                ('address', models.CharField(default='Default Address', max_length=255)),
                ('location', models.CharField(default='Default Location', max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('api.user',),
        ),
    ]
