# Generated by Django 5.0.6 on 2024-05-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.RemoveField(
            model_name='user3',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='managementLevel',
        ),
        migrations.AddField(
            model_name='user1',
            name='address',
            field=models.CharField(default='Default Address', max_length=255),
        ),
        migrations.AddField(
            model_name='user1',
            name='firstName',
            field=models.CharField(default='Default firstName', max_length=100),
        ),
        migrations.AddField(
            model_name='user1',
            name='lastName',
            field=models.CharField(default='Default lastName', max_length=100),
        ),
        migrations.DeleteModel(
            name='User2',
        ),
        migrations.DeleteModel(
            name='User3',
        ),
    ]
