# Generated by Django 5.0.6 on 2024-05-25 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_area_remove_user3_user_ptr_remove_user1_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fullname',
        ),
    ]
